# Generated by Django 4.1.12 on 2025-01-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cancelledorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='products_files/')),
                ('id_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_file', to='shop.product')),
            ],
        ),
    ]
