# Generated by Django 4.1.12 on 2025-01-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('fixed', 'fixed'), ('custom', 'custom'), ('consult', 'consult')], default='fixed', max_length=10),
        ),
    ]
