# Generated by Django 4.1.12 on 2025-01-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_consult_selectiontimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='active',
            field=models.BooleanField(default=0),
        ),
    ]
