version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:${MYSQL_PORT}" #host:container
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/
    container_name: stellium_db
    hostname: ${MYSQL_HOST}

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy   
    env_file:
      - .env
    command: sh /app/config/entrypoint.dev.sh
    volumes:
      - .:/app
      - /logs/:/app/stellium/logs
    container_name: stellium_web

volumes:
  db_data:
  logs: